### ISSUE TITLE
Оставшиеся замечания по коду

### ISSUE THREAD

**Issue by sergey-shambir** [eligantRU/clock#6]
1. Это лучше поместить в stdafx.h

``` cpp
#define _USE_MATH_DEFINES
#include <cmath>
#include <windows.h>
```

Тогда можно почистить include в 
- main.cpp
1. Надо убрать из main.cpp строку `#include "clock.cpp"`
2. Предлагаю обеспечить в `struct Clock` большую гибкость
- убрать `time_t sysTime`, оставить только `tm locTime`
- убрать `setSysTime`, `setLocTime`, оставить только `setTime(tm value)`
- `update` можно тоже убрать, т.к. часы пассивны и не содержат внутреннего поведения, которое следовало бы продвинуть на deltaTime вперёд.
1. Почему `void setCirclesSec(sf::CircleShape * circlesSec);`, `void setCirclesHour(sf::CircleShape * circlesHour);`, `void setNumHour(sf::Text * numHour);` принимают указатели? Можно изменить тип соответствующих полей на `std::array<sf::Text, 12>` и то же самое передавать в приватные функции
2. correctPosition лучше назвать fixPosition (более общепринятое слово fix), `std::string` надо передавать по константной ссылке
3. Часто встречается одно выражение: `sec * M_PI / 180`, которое легко обозначить фразой "перевод в радианы". Пора завести функцию.
4. Вместо `float(cos(x))` можно писать cos(x), если x имеет тип float. Без разницы, будет ли x выражением, переменной, константой или результатом выполнения функции.

**Comment by eligantRU** [comment]
Замечания устранены, за исключение update

Аргументирую: часы как раз-таки и нужно апдейтить каждую секунду, deltaTime неявно задана
К тому же, это отличная обёртка. В противном случае само управление стрелками придётся вынести в public, что недопустимо
